language: objective-c
osx_image: xcode10.3
cache:
  bundler: true
  directories:
    - Carthage
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - bundle exec fastlane ios tests
